# Language spec
language: scala
sudo: true

# Scala version
scala:
  - "2.12.4"

# Supported jdk
jdk:
  - openjdk8
  - oraclejdk8

# Mount docker service
services:
  - docker

# Use local
before_install:
  - docker-compose up -d
  - unset SBT_OPTS JVM_OPTS
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats awk

# Run
script:
  - bats core/src/test/bash
  - chmod -R +x sbt sbt-dist/* scripts/*
  - ./sbt -batch -mem 2048 clean
  - ./sbt -batch -mem 2048 scalastyle
  - ./sbt -batch -mem 2048 compile
  - ./sbt -batch -mem 2048 ";coverage;test;coverageReport;coverageAggregate"

# Upload codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Caching
before_cache:
  - 'find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete'
  - 'find $HOME/.sbt  -name "*.lock"               -print -delete'
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot'

# Notify
notifications:
  email: false
