# Language spec
language: scala
sudo: false

# Scala version
scala:
  - "2.12.2"

# Supported jdk
jdk:
  - openjdk8
  - oraclejdk8

# Use local
before_install: unset SBT_OPTS JVM_OPTS

# Run
script:
  - chmod -R +x sbt sbt-dist/* scripts/*
  - ./sbt ";test:compile;scalastyle"

# Caching
before_cache:
  - 'find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete'
  - 'find $HOME/.sbt  -name "*.lock"               -print -delete'
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot'

# Notify
notifications:
  email: false
